import Link from 'next/link';
import { Download, Eye, EyeOff, FileText, Sparkles, Trash2 } from 'lucide-react';
import {
  DOCUMENT_CATEGORY_LABELS,
  formatBytes,
  groupDocumentsByCategory,
  isImage,
} from '@/lib/storage/storage-core';
import { deleteDocument, toggleDocumentVisibility } from '@/lib/media/actions';
import type { DocumentRow } from '@/lib/media/queries';
import { Button } from '@/components/ui/button';

/**
 * Project documents, filed by category. Downloads go through a short-lived
 * signed URL minted for this render — a link copied out of the page stops
 * working in minutes, which is the point of a private bucket.
 */
export function DocumentList({
  documents,
  mayWrite,
  showProject = false,
}: {
  documents: DocumentRow[];
  mayWrite: boolean;
  showProject?: boolean;
}) {
  if (documents.length === 0) {
    return <p className="text-sm text-muted-foreground">No documents yet.</p>;
  }

  const groups = groupDocumentsByCategory(documents);

  return (
    <div className="space-y-4">
      {groups.map((group) => (
        <section key={group.category} className="space-y-2">
          <h3 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
            {group.label}
            <span className="ml-1.5 font-normal">{group.documents.length}</span>
          </h3>
          <ul className="divide-y rounded-md border">
            {group.documents.map((doc) => (
              <li key={doc.id} className="flex flex-wrap items-start gap-2 px-3 py-2">
                <FileText className="mt-0.5 h-4 w-4 flex-none text-muted-foreground" />
                <div className="min-w-0 flex-1">
                  <div className="flex flex-wrap items-center gap-1.5">
                    <span className="truncate text-sm font-medium">{doc.fileName}</span>
                    {doc.isGenerated ? (
                      <span
                        className="inline-flex items-center gap-0.5 rounded px-1 py-0.5 text-[10px] font-medium text-muted-foreground ring-1 ring-inset ring-border"
                        title="Generated by the system, not uploaded"
                      >
                        <Sparkles className="h-2.5 w-2.5" />
                        Generated
                      </span>
                    ) : null}
                    {doc.clientVisible ? (
                      <span className="rounded bg-emerald-500/15 px-1.5 py-0.5 text-[10px] font-medium text-emerald-700 dark:text-emerald-300">
                        Client
                      </span>
                    ) : null}
                  </div>
                  <p className="text-xs text-muted-foreground">
                    {formatBytes(doc.sizeBytes)}
                    {isImage(doc.mimeType) ? ' · image' : ''} ·{' '}
                    {new Date(doc.createdAt).toLocaleDateString('en-US')}
                    {doc.uploaderName ? ` · ${doc.uploaderName}` : ''}
                    {showProject && doc.projectName ? (
                      <>
                        {' · '}
                        <Link href={`/projects/${doc.projectId}`} className="hover:underline">
                          {doc.projectNumber ?? doc.projectName}
                        </Link>
                      </>
                    ) : null}
                  </p>
                  {doc.notes ? <p className="mt-0.5 text-xs">{doc.notes}</p> : null}
                </div>

                <div className="flex flex-none flex-wrap gap-1">
                  {doc.url ? (
                    <a
                      href={doc.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex h-7 items-center gap-1 rounded-md border px-2 text-xs transition-colors hover:bg-accent"
                      title={`Open ${doc.fileName}`}
                    >
                      <Download className="h-3 w-3" />
                      Open
                    </a>
                  ) : (
                    <span className="inline-flex h-7 items-center px-2 text-xs text-muted-foreground">
                      Unavailable
                    </span>
                  )}
                  {mayWrite ? (
                    <>
                      <form action={toggleDocumentVisibility}>
                        <input type="hidden" name="documentId" value={doc.id} />
                        <input type="hidden" name="visible" value={String(!doc.clientVisible)} />
                        <Button
                          type="submit"
                          size="sm"
                          variant="outline"
                          className="h-7 w-auto px-2 text-xs"
                          title={
                            doc.clientVisible
                              ? 'Hide this from the client'
                              : 'Show this to the client'
                          }
                        >
                          {doc.clientVisible ? (
                            <EyeOff className="h-3 w-3" />
                          ) : (
                            <Eye className="h-3 w-3" />
                          )}
                        </Button>
                      </form>
                      <form action={deleteDocument}>
                        <input type="hidden" name="documentId" value={doc.id} />
                        <Button
                          type="submit"
                          size="sm"
                          variant="outline"
                          className="h-7 w-auto px-2 text-xs text-destructive"
                          title={`Remove ${doc.fileName}`}
                        >
                          <Trash2 className="h-3 w-3" />
                        </Button>
                      </form>
                    </>
                  ) : null}
                </div>
              </li>
            ))}
          </ul>
        </section>
      ))}
    </div>
  );
}

/** Category label helper for callers that only need the text. */
export function documentCategoryLabel(category: keyof typeof DOCUMENT_CATEGORY_LABELS): string {
  return DOCUMENT_CATEGORY_LABELS[category];
}
